import soccer from "../../public/assets/soccerBall.png";
import closeUpBasket from "../../public/assets/closeBasketBall.png";
import sportCar from "../../public/assets/sportCar.png";
import redPing from "../../public/assets/redPing.png";
import football from "../../public/assets/football.jpg";
import basketball2 from "../../public/assets/Basketball.jpg";
import carSport from "../../public/assets/carSport.jpg";
import tableTennis from "../../public/assets/tableTennis.jpg";
import basketball from "../../public/assets/basketballequipment.png";
import hockey from "../../public/assets/hockeyplayers.png";
import badminton from "../../public/assets/badminton.png";
import venue from "../../public/assets/vennue1.jpg";
import venue1 from "../../public/assets/venue2.avif";
import venue2 from "../../public/assets/venue3.avif";
import venue3 from "../../public/assets/venue4.avif";
import venue4 from "../../public/assets/venue5.avif";
import venue5 from "../../public/assets/venue6.avif";
import PlayerImage from "../../public/assets/runnerPlayer.png";
import FastAcc from "../../public/assets/fastAcc.png";
import footballground1 from "../../public/assets/football_ground1.webp";
import footballground2 from "../../public/assets/footballground2.jpg";

import updates from "../../public/assets/update.png";
import invoice from "../../public/assets/invoicing.png";
import customizeVenues from "../../public/assets/customizesVenue.png";
import { LinksType } from "@/interfaces";

export const CATEGORY_DATA = [
  { text: "Football", img: [soccer, football] },
  { text: "Basketball", img: [closeUpBasket, basketball2] },
  { text: "Car Sport", img: [sportCar, carSport] },
  { text: "Table Tennis", img: [redPing, tableTennis] },
];
export const SOCIAL = [
  { media: "Facebook", text: "facebook" },
  { media: "Instagram", text: "instagram" },
  { media: "Twitter", text: "twitter" },
  { media: "Linkedin", text: "linkedin" },
];
export const INPUT_FIELDS = [
  {
    name: "location",
    type: "text",
    placeholder: "Location",
    label: "Location",
  },
  {
    name: "sport",
    type: "select",
    placeholder: "Sport",
    label: "Sport",
  },
  {
    name: "date",
    type: "date",
    placeholder: "Date",
    label: "Date",
  },
  {
    name: "timeSlot",
    type: "select",
    placeholder: "Time",
    label: "Slot",
  },
];
export const DATA = [
  { text: "Privacy Policies", link: "/privacy-policies" },
  { text: "Terms Of Services", link: "/terms-services" },
  { text: "Cookies Settings", link: "/cookies" },
];
export const SPORTS = [
  "Badminton",
  "Tennis",
  "Football",
  "Basketball",
  "Cricket",
  "Volleyball",
];
export const TIMESLOTS = [
  "Morning: 7AM - 11AM",
  "Evening: 6PM - 12AM",
  "Afternoon: 12PM - 4PM",
  "Evening: 6PM - 10PM",
];

export const TRENDING = [
  {
    text: "Race98 - 03 June 2023",
    img: PlayerImage,
    details: "Ethiopian runners took the top four spots.",
  },
  {
    text: "INDYCAR - 03 June 2023",
    img: FastAcc,
    details: "IndyCar Detroit: Dixon quickest in second practice",
  },
];
export const LINKS: LinksType = {
  UsefullLinks: [
    { id: 1, text: "About Us", route: "/about-us" },
    { id: 2, text: "Contact", route: "/about-us#contact-us" },
    { id: 3, text: "Venues", route: "/venues" },
  ],

  // Category: [
  //   { text: "football" },
  //   { text: "Badminton" },
  //   { text: "BasketBall" },
  // ],

  FollowUs: [
    { media: "Facebook", text: "facebook" },
    { media: "Instagram", text: "instagram" },
    { media: "Twitter", text: "twitter" },
    { media: "Linkedin", text: "linkedin" },
  ],
};
export const VENUES = [
  {
    id: 1,
    game: "BasketBall",
    img: badminton,
    venueName: "AIM Badminton Academy",
    reviews: 18,
    desc: "AIM Badminton Academy offers world-class indoor courts with wooden flooring, proper lighting, and coaching sessions for all levels.",
  },
  {
    id: 2,
    game: "Badminton",
    img: basketball,
    venueName: "Smash Arena",
    reviews: 25,
    desc: "Smash Arena provides air-conditioned courts with synthetic flooring and professional coaches available for training.",
  },
  {
    id: 3,
    game: "Tennis",
    img: hockey,
    venueName: "Green Valley Tennis Club",
    reviews: 12,
    desc: "Premium clay and hard tennis courts available with night lighting and weekend tournaments.",
  },
  {
    id: 4,
    game: "Cricket",
    img: badminton,
    venueName: "Legends Cricket Ground",
    reviews: 30,
    desc: "Full-size cricket ground with turf and cement pitches, net practice areas, and seasonal leagues.",
  },
  {
    id: 5,
    game: "Football",
    img: hockey,
    venueName: "Strikers Football Arena",
    reviews: 21,
    desc: "Synthetic grass football ground with floodlights and locker room facilities.",
  },
  {
    id: 6,
    game: "Table Tennis",
    img: badminton,
    venueName: "Spin & Smash Center",
    reviews: 15,
    desc: "Indoor table tennis setup with ITTF-approved tables and regular coaching workshops.",
  },
  {
    id: 7,
    game: "Swimming",
    img: basketball,
    venueName: "Blue Dolphin Pool",
    reviews: 19,
    desc: "Olympic-size pool with temperature control, safety lifeguards, and training for all age groups.",
  },
  {
    id: 8,
    game: "Volleyball",
    img: badminton,
    venueName: "SmashVolley Court",
    reviews: 10,
    desc: "Beach-style sand volleyball courts available for casual and league matches.",
  },
  {
    id: 9,
    game: "Skating",
    img: hockey,
    venueName: "RollerZ Skate Park",
    reviews: 14,
    desc: "Smooth indoor skating track with gear rentals and professional trainers.",
  },
  {
    id: 10,
    game: "Boxing",
    img: basketball,
    venueName: "Fight Club Arena",
    reviews: 23,
    desc: "Fully equipped boxing gym with sparring rings, bags, and certified coaches.",
  },
  {
    id: 11,
    game: "Archery",
    img: badminton,
    venueName: "Eagle Eye Archery Center",
    reviews: 8,
    desc: "Dedicated archery range with modern equipment and personalized coaching.",
  },
  {
    id: 12,
    game: "Karate",
    img: basketball,
    venueName: "Dojo Warriors Studio",
    reviews: 11,
    desc: "Traditional karate training with belt progression programs and experienced masters.",
  },
  {
    id: 13,
    game: "Yoga",
    img: badminton,
    venueName: "Zen Yoga Hall",
    reviews: 20,
    desc: "Spacious indoor yoga center with certified instructors and peaceful ambiance.",
  },
  {
    id: 14,
    game: "Gymnastics",
    img: hockey,
    venueName: "Flex Gymnastics Academy",
    reviews: 13,
    desc: "State-of-the-art gymnastic arena with balance beams, vaults, and trained coaches.",
  },
  {
    id: 15,
    game: "Martial Arts",
    img: basketball,
    venueName: "Iron Fist Combat Studio",
    reviews: 9,
    desc: "Mixed martial arts classes including jiu-jitsu, taekwondo, and kickboxing.",
  },
  {
    id: 16,
    game: "Kabaddi",
    img: badminton,
    venueName: "Desi Arena",
    reviews: 6,
    desc: "Traditional kabaddi ground with training camps and youth leagues.",
  },
  {
    id: 17,
    game: "Squash",
    img: basketball,
    venueName: "Ace Squash Club",
    reviews: 16,
    desc: "Indoor squash courts with temperature control and booking system.",
  },
  {
    id: 18,
    game: "Golf",
    img: hockey,
    venueName: "Royal Greens Golf Club",
    reviews: 28,
    desc: "18-hole championship golf course with clubhouse, caddy services, and lessons.",
  },
  {
    id: 19,
    game: "Hockey",
    img: basketball,
    venueName: "Blades Hockey Rink",
    reviews: 17,
    desc: "Turf-based hockey field with coaching for schools and local teams.",
  },
  {
    id: 20,
    game: "Running",
    img: hockey,
    venueName: "TrackOn Stadium",
    reviews: 22,
    desc: "400m synthetic track with lighting, hydration stations, and fitness events.",
  },
];
export const DETAILS = [
  {
    id: 1,
    venueName: "AIM Badminton Academy",
    rating: 4.5,
    loc: "Delhi, India",
    cost: "₹ 200.00",
    distance: 0.5,
    img: [venue, venue1, venue2],
    amenties: ["Parking", "Warm Up Area"],
    sport: ["Badminton", "Tennis"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "AIM Badminton Academy offers world-class indoor courts with wooden flooring, proper lighting, and coaching sessions for all levels.",
    multiImg: [footballground1, venue, footballground2],
    reviews: 18,
  },
  {
    id: 2,
    venueName: "City Sports Arena",
    rating: 4.2,
    loc: "555 California St, San Francisco, USA",
    cost: "₹ 350.00",
    distance: 2.8,
    img: [venue1, venue2, venue3],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-04-19",
    timeSlot: "Evening: 12PM - 6PM",
    desc: "A premium facility in San Francisco featuring artificial turf football fields, indoor basketball courts, and cricket nets.",
    multiImg: [footballground1, venue, footballground2],
    reviews: 25,
    amenties: ["Parking", "Warm Up Area", "Flood Light"],
  },
  {
    id: 3,
    venueName: "Bangalore Kickoff Grounds",
    rating: 4.6,
    loc: "Bangalore, India",
    cost: "₹ 300.00",
    distance: 3.0,
    img: [venue2, venue4, venue],
    sport: ["Football", "Volleyball"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "Sprawling football ground with night lighting, artificial turf, and ample parking located in the heart of Bangalore.",
    multiImg: [footballground1, venue, footballground2],
    reviews: 30,
    amenties: ["Parking", "Flood Light"],
  },
  {
    id: 4,
    venueName: "Raipur Indoor Stadium",
    rating: 4.3,
    loc: "Raipur, India",
    cost: "₹ 150.00",
    distance: 2.5,
    img: [venue3, venue5, venue1],
    sport: ["Basketball", "Badminton", "Cricket"],
    date: "2025-04-11",
    timeSlot: "Afternoon: 2PM - 6PM",
    desc: "This indoor sports complex offers well-maintained courts, changing rooms, and refreshment areas for all ages.",
    multiImg: [footballground1, venue, footballground2],
    reviews: 21,
    amenties: ["Parking", "Flood Light", "Washroom"],
  },
  {
    id: 5,
    venueName: "Jaipur MultiSport Park",
    rating: 4.7,
    loc: "Jaipur, India",
    cost: "₹ 250.00",
    distance: 1.8,
    img: [venue4, venue2, venue3],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "A state-of-the-art venue in Jaipur with synthetic courts, open grounds, and equipment rental facilities.",
    multiImg: [footballground1, venue, footballground2],
    reviews: 35,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 6,
    venueName: "Elite Arena",
    rating: 4.8,
    loc: "Mumbai, India",
    cost: "₹ 400.00",
    distance: 4.0,
    img: [venue5, venue, venue3],
    sport: ["Tennis", "Football", "Basketball"],
    date: "2025-04-11",
    timeSlot: "Evening: 4PM - 10PM",
    desc: "Elite Arena offers professional-level courts and fields with seating for spectators and locker facilities.",
    multiImg: [footballground1, venue, footballground2],
    reviews: 40,

    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 7,
    venueName: "The Royal Oak",
    rating: 4.7,
    loc: "Delhi",
    cost: "₹ 30.00",
    distance: 0.5,
    img: [venue1, venue2, venue3],
    sport: ["Football", "Badminton"],
    date: "2025-05-15",
    timeSlot: "Evening: 6PM - 12AM",
    desc: "The Royal Oak is a luxurious banquet hall perfect for grand events. Located in the heart of Connaught Place, it offers a rich atmosphere for celebrations.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 120,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 8,
    venueName: "Sky Lounge",
    rating: 4.6,
    loc: "Mumbai",
    cost: "₹ 35.00",
    distance: 3.2,
    img: [venue2, venue3, venue5],
    sport: ["Football", "Basketball", "Tennis"],
    date: "2025-05-16",
    timeSlot: "Night: 6PM - 12AM",
    desc: "Sky Lounge is a rooftop venue offering stunning views of the city skyline. Ideal for intimate events or corporate gatherings.",
    multiImg: [footballground1, venue5, footballground2],
    reviews: 145,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 9,
    venueName: "The Celebration Point",
    rating: 4.8,
    loc: "Jaipur",
    cost: "₹ 25.00",
    distance: 1.5,
    img: [venue4, venue1, venue2],
    sport: ["Football", "Cricket", "Basketball"],
    date: "2025-05-18",
    timeSlot: "Morning: 7AM - 12PM",
    desc: "A beautiful garden venue perfect for weddings and outdoor events. It combines elegance with nature's tranquility.",
    multiImg: [footballground1, venue3, footballground2],
    reviews: 200,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 10,
    venueName: "Blue Sapphire Convention Centre",
    rating: 4.9,
    loc: "Bengaluru",
    cost: "₹ 50.00",
    distance: 4.2,
    img: [venue5, venue1, venue2],
    sport: ["Football", "Basketball", "Volleyball"],
    date: "2025-05-20",
    timeSlot: "Afternoon: 12PM - 5PM",
    desc: "An exquisite convention centre with state-of-the-art facilities for conferences, trade shows, and seminars.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 300,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 11,
    venueName: "Vivanta Hall",
    rating: 4.6,
    loc: "Hyderabad",
    cost: "₹ 20.00",
    distance: 1.8,
    img: [venue3, venue5, venue4],
    sport: ["Football", "Cricket", "Tennis"],
    date: "2025-05-22",
    timeSlot: "Evening: 6PM - 11PM",
    desc: "Vivanta Hall is known for its classic design and warm ambiance, making it perfect for weddings and corporate events.",
    multiImg: [footballground1, venue2, footballground2],
    reviews: 175,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 12,
    venueName: "The Open Courtyard",
    rating: 4.7,
    loc: "Pune",
    cost: "₹ 18.00",
    distance: 2.3,
    img: [venue1, venue3, venue2],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-05-25",
    timeSlot: "Morning: 6AM - 11AM",
    desc: "A charming outdoor venue surrounded by greenery. Ideal for hosting morning events, picnics, or sports activities.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 130,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 13,
    venueName: "Emerald Enclave",
    rating: 4.6,
    loc: "Chandigarh",
    cost: "₹ 22.00",
    distance: 1.2,
    img: [venue4, venue5, venue3],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-05-28",
    timeSlot: "Afternoon: 1PM - 5PM",
    desc: "Emerald Enclave offers a stunning combination of indoor and outdoor spaces, making it versatile for different events.",
    multiImg: [footballground1, venue2, footballground2],
    reviews: 180,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 14,
    venueName: "Luxe Imperial",
    rating: 4.8,
    loc: "Lucknow",
    cost: "₹ 45.00",
    distance: 5.4,
    img: [venue2, venue4, venue5],
    sport: ["Football", "Cricket", "Volleyball"],
    date: "2025-06-01",
    timeSlot: "Morning: 8AM - 12PM",
    desc: "Luxe Imperial is a grand venue perfect for corporate events, weddings, and other significant celebrations.",
    multiImg: [footballground1, venue3, footballground2],
    reviews: 220,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 15,
    venueName: "Golden Palm",
    rating: 4.7,
    loc: "Ahmedabad",
    cost: "₹ 20.00",
    distance: 3.6,
    img: [venue1, venue3, venue5],
    sport: ["Football", "Tennis", "Basketball"],
    date: "2025-06-05",
    timeSlot: "Evening: 5PM - 9PM",
    desc: "An elegantly designed venue for all kinds of events, from family gatherings to corporate events.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 165,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 16,
    venueName: "Misty Meadows",
    rating: 4.5,
    loc: "Bhopal",
    cost: "₹ 15.00",
    distance: 2.8,
    img: [venue2, venue3, venue1],
    sport: ["Football", "Cricket", "Tennis"],
    date: "2025-06-08",
    timeSlot: "Morning: 6AM - 11AM",
    desc: "Misty Meadows is a serene outdoor venue surrounded by nature, ideal for morning events and small gatherings.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 90,

    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 17,
    venueName: "Crown Palace",
    rating: 4.6,
    loc: "Kolkata",
    cost: "₹ 28.00",
    distance: 3.0,
    img: [venue4, venue5, venue2],
    sport: ["Football", "Badminton", "Cricket"],
    date: "2025-06-12",
    timeSlot: "Afternoon: 12PM - 4PM",
    desc: "Crown Palace is a majestic venue, offering the perfect space for weddings and corporate functions.",
    multiImg: [footballground1, venue3, footballground2],
    reviews: 210,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 18,
    venueName: "Sunset Arena",
    rating: 4.7,
    loc: "Goa",
    cost: "₹ 50.00",
    distance: 1.5,
    img: [venue3, venue1, venue5],
    sport: ["Football", "Basketball", "Tennis"],
    date: "2025-06-15",
    timeSlot: "Evening: 5PM - 9PM",
    desc: "Sunset Arena is a high-end venue perfect for evening events. It offers a stunning view of the beach and a relaxed atmosphere.",
    multiImg: [footballground1, venue2, footballground2],
    reviews: 250,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 19,
    venueName: "The Oasis Garden",
    rating: 4.5,
    loc: "Surat",
    cost: "₹ 12.00",
    distance: 4.2,
    img: [venue4, venue5, venue2],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-06-18",
    timeSlot: "Morning: 7AM - 11AM",
    desc: "A beautiful outdoor venue, ideal for intimate garden parties and small gatherings.",
    multiImg: [footballground1, venue1, footballground2],
    reviews: 130,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 20,
    venueName: "Palatial Ballroom",
    rating: 4.8,
    loc: "Chennai",
    cost: "₹ 60.00",
    distance: 6.3,
    img: [venue3, venue4, venue5],
    sport: ["Football", "Badminton", "Tennis"],
    date: "2025-06-22",
    timeSlot: "Evening: 6PM - 12AM",
    desc: "Palatial Ballroom offers a luxurious indoor venue perfect for weddings, gala dinners, and corporate events.",
    multiImg: [footballground1, venue2, footballground2],
    reviews: 280,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 21,
    venueName: "Lush Lawn",
    rating: 4.4,
    loc: "Indore",
    cost: "₹ 14.00",
    distance: 2.0,
    img: [venue5, venue2, venue4],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-06-25",
    timeSlot: "Afternoon: 12PM - 4PM",
    desc: "A vibrant lawn perfect for sports events, family gatherings, and outdoor activities.",
    multiImg: [footballground1, venue1, footballground2],
    reviews: 145,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 22,
    venueName: "Tranquil Terrace",
    rating: 4.7,
    loc: "Vadodara",
    cost: "₹ 19.00",
    distance: 3.1,
    img: [venue1, venue5, venue3],
    sport: ["Football", "Cricket", "Basketball"],
    date: "2025-07-01",
    timeSlot: "Morning: 7AM - 11AM",
    desc: "A peaceful terrace venue perfect for brunches, yoga sessions, and relaxed events.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 110,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 23,
    venueName: "The Velvet Garden",
    rating: 4.8,
    loc: "Nagpur",
    cost: "₹ 24.00",
    distance: 2.4,
    img: [venue4, venue1, venue5],
    sport: ["Football", "Cricket", "Badminton"],
    date: "2025-07-05",
    timeSlot: "Evening: 6PM - 10PM",
    desc: "An elegant garden with a combination of greenery and modern amenities, perfect for weddings and evening events.",
    multiImg: [footballground1, venue2, footballground2],
    reviews: 195,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 24,
    venueName: "Serenity Bay",
    rating: 4.9,
    loc: "Kochi",
    cost: "₹ 75.00",
    distance: 4.5,
    img: [venue5, venue3, venue1],
    sport: ["Football", "Cricket", "Tennis"],
    date: "2025-07-10",
    timeSlot: "Afternoon: 12PM - 4PM",
    desc: "Serenity Bay offers an exclusive experience with its beachfront location and elegant venue for events of all sizes.",
    multiImg: [footballground1, venue4, footballground2],
    reviews: 310,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
  {
    id: 25,
    venueName: "Diamond Garden",
    rating: 4.6,
    loc: "Raipur",
    cost: "₹ 17.00",
    distance: 1.9,
    img: [venue1, venue4, venue2],
    sport: ["Football", "Basketball", "Cricket"],
    date: "2025-07-15",
    timeSlot: "Morning: 7AM - 11AM",
    desc: "Diamond Garden is an ideal venue for both indoor and outdoor events, featuring ample green spaces for sports and leisure.",
    multiImg: [footballground1, venue3, footballground2],
    reviews: 175,
    amenties: ["Parking", "Flood Light", "Washroom", "Warm Up Area"],
  },
];
export const VENUE_IMAGE = [
  { id: 1, img: venue1 },
  { id: 2, img: venue2 },
  { id: 3, img: venue3 },
];

export const FEATURES = [
  { id: 1, feature: "Venues", frequency: 120 },
  { id: 2, feature: "Sports", frequency: 20 },
  { id: 3, feature: "Reviews", frequency: 2000 },
];

export const FEATURE_DATA = [
  { id: 1, feature: "Online Payments", img: invoice },
  { id: 2, feature: "Real-Time Availability Updates", img: updates },
  { id: 3, feature: "Invoicing", img: invoice },
  { id: 4, feature: "Customisable Venue Profiles", img: customizeVenues },
  { id: 5, feature: "Mobile App Management", img: invoice },
  { id: 6, feature: "Protection from no-shows", img: updates },
  { id: 7, feature: "Customer Support", img: invoice },
  { id: 8, feature: "Dynamic QR", img: customizeVenues },
  { id: 9, feature: "Enhanced Marketing Exposure", img: invoice },
];

export const USER_PROFILE = [
  { id: 1, link: "Profile", route: "/profile" },
  { id: 2, link: "Booking", route: "/user-booking" },
  { id: 3, link: "FAQ", route: "/faq" },
  { id: 4, link: "Logout", route: "/" },
];

export const VENUES_HISTORY = [
  {
    id: 1,
    name: "National Sports Complex",
    location: "New Delhi, India",
    date: "2025-03-18",
    status: "Visited",
    sport: "football",
    image: venue,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 2,
    name: "Rajiv Indoor Stadium",
    location: "Mumbai, India",
    date: "2025-04-05",
    status: "Booked",
    sport: "badminton",
    image: venue1,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 3,
    name: "Greenfield Arena",
    location: "Kochi, India",
    date: "2025-01-22",
    status: "Cancelled",
    sport: "cricket",
    image: venue2,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 4,
    name: "Eden Gardens",
    location: "Kolkata, India",
    date: "2025-02-10",
    status: "Visited",
    sport: "cricket",
    image: venue3,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 5,
    name: "Sardar Patel Stadium",
    location: "Ahmedabad, India",
    date: "2025-06-12",
    status: "Booked",
    sport: "cricket",
    image: venue4,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 6,
    name: "Indira Gandhi Arena",
    location: "New Delhi, India",
    date: "2025-07-08",
    status: "Booked",
    sport: "football",
    image: venue5,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 7,
    name: "Gachibowli Stadium",
    location: "Hyderabad, India",
    date: "2025-03-28",
    status: "Visited",
    sport: "football",
    image: venue2,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 8,
    name: "JRD Tata Sports Complex",
    location: "Jamshedpur, India",
    date: "2025-04-18",
    status: "Booked",
    sport: "football",
    image: venue3,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 9,
    name: "Shree Shiv Chhatrapati Sports Complex",
    location: "Pune, India",
    date: "2025-05-02",
    status: "Cancelled",
    sport: "badminton",
    image: venue1,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 10,
    name: "Thyagaraj Sports Complex",
    location: "New Delhi, India",
    date: "2025-06-20",
    status: "Booked",
    sport: "badminton",
    image: venue5,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 11,
    name: "Salt Lake Stadium",
    location: "Kolkata, India",
    date: "2025-07-15",
    status: "Visited",
    sport: "football",
    image: venue4,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },

    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 12,
    name: "Jawaharlal Nehru Stadium",
    location: "Chennai, India",
    date: "2025-08-01",
    status: "Booked",
    sport: "cricket",
    image: venue3,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 13,
    name: "Birsa Munda Hockey Stadium",
    location: "Rourkela, India",
    date: "2025-08-14",
    status: "Booked",
    sport: "football",
    image: venue1,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 14,
    name: "Kalinga Stadium",
    location: "Bhubaneswar, India",
    date: "2025-09-01",
    status: "Cancelled",
    sport: "badminton",
    image: venue2,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 15,
    name: "Indira Gandhi Athletic Stadium",
    location: "Guwahati, India",
    date: "2025-09-10",
    status: "Booked",
    sport: "football",
    image: venue4,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 16,
    name: "Guru Nanak Stadium",
    location: "Ludhiana, India",
    date: "2025-10-01",
    status: "Booked",
    sport: "football",
    image: venue5,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 17,
    name: "Chinnaswamy Stadium",
    location: "Bengaluru, India",
    date: "2025-10-20",
    status: "Visited",
    sport: "cricket",
    image: venue1,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 18,
    name: "MA Chidambaram Stadium",
    location: "Chennai, India",
    date: "2025-11-01",
    status: "Booked",
    sport: "cricket",
    image: venue4,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 19,
    name: "Balewadi Stadium",
    location: "Pune, India",
    date: "2025-11-20",
    status: "Booked",
    sport: "football",
    image: venue2,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
  {
    id: 20,
    name: "Guru Gobind Singh Stadium",
    location: "Jalandhar, India",
    date: "2025-12-01",
    status: "Cancelled",
    sport: "badminton",
    image: venue3,
    price: {
      subTotal: 800,
      tax: 20.0,
      bookingFees: 200,
      total: 1000,
    },
    timeSlots: [
      {
        id: 1,
        sport: "badminton",
        court: "A",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "4:00 PM",
        checkOut: "5:00 PM",
      },
      {
        id: 2,
        sport: "badminton",
        court: "B",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "5:00 PM",
        checkOut: "6:00 PM",
      },
      {
        id: 3,
        sport: "badminton",
        court: "C",
        date: "2025-05-20",
        time: "1 hour",
        checkIn: "6:00 PM",
        checkOut: "7:00 PM",
      },
    ],
  },
];

export const FAQ = [
  {
    question: "What is the cancellation policy?",
    answer:
      "You can cancel your booking up to 24 hours in advance for a full refund.",
  },
  {
    question: "How do I change my booking date?",
    answer:
      "You can reschedule your booking by going to your booking history and selecting 'Reschedule'.",
  },
  {
    question: "Are there any discounts for group bookings?",
    answer:
      "Yes, we offer discounts for groups of 5 or more. Please contact support for more details.",
  },
  {
    question: "Is parking available at the venues?",
    answer:
      "Yes, most venues offer parking. Check venue details before booking.",
  },
  {
    question: "Can I bring outside food or drinks?",
    answer: "This depends on the venue policy. Please check the rules section.",
  },
  {
    question: "Do I need to bring my own equipment?",
    answer:
      "Some venues provide equipment, but it’s best to confirm beforehand.",
  },
  {
    question: "What payment methods are accepted?",
    answer: "We accept UPI, debit/credit cards, and net banking.",
  },
  {
    question: "Can I book for someone else?",
    answer: "Yes, just enter their name and details while booking.",
  },
  {
    question: "What happens in case of rain?",
    answer:
      "Outdoor bookings may be rescheduled or refunded in case of weather disruption.",
  },
  {
    question: "How do I contact support?",
    answer: "You can reach us through the 'Help & Support' section in the app.",
  },
];

export const sportIcons = {
  football: "fas fa-futbol",
  badminton: "fas fa-table-tennis",
  cricket: "fas fa-baseball-ball",
};

export const statusColors = {
  Booked: "bg-amber-100 text-amber-800 border border-amber-300",
  Visited: "bg-green-100 text-green-800 border border-green-300",
  Cancelled: "bg-red-100 text-red-800 border border-red-300",
};
