import venue from "../../public/assets/img3.jpeg";
export const details = [
  {
    venueName: "Football, Basketball Venue",
    rating: 4.5,
    loc: "Australia",
    cost: "$ 20.00",
    time: "30mins",
    distance: 0.2,
    img: venue,
    sport: "football",
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
  },
  {
    venueName: "Football, Basketball Venue",
    rating: 4.5,
    loc: "Delhi",
    cost: "$ 20.00",
    time: "30mins",
    distance: 3,
    img: venue,
    sport: "Circket",
    date: "2025-04-19",
    timeSlot: "Evening: 12PM - 6PM",
  },
  {
    venueName: "Football, Basketball Venue",
    rating: 4.5,
    loc: "Banglore",
    cost: "$ 20.00",
    time: "30mins",
    distance: 3,
    img: venue,
    sport: "football",
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
  },
  {
    venueName: "Football, Basketball Venue",
    rating: 4.5,
    loc: "America",
    cost: "$ 20.00",
    time: "30mins",
    distance: 3,
    img: venue,
    sport: "football",
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
  },
  {
    venueName: "Football, Basketball Venue",
    rating: 4.5,
    loc: "Mount Larcom QLD 4695, Australia",
    cost: "$ 20.00",
    time: "30mins",
    distance: 3,
    img: venue,
    sport: "football",
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
  },
  {
    venueName: "Football, Basketball Venue",
    rating: 4.5,
    loc: "Mount Larcom QLD 4695, Australia",
    cost: "$ 20.00",
    time: "30mins",
    distance: 3,
    img: venue,
    sport: "football",
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
  },
];
