import venue from "../../public/assets/img3.jpeg";
import footballground1 from "../../public/assets/football_ground1.webp";
import footballground2 from "../../public/assets/footballground2.jpg";

export const details = [
  {
    id: 1,
    venueName: "abc Venue",
    rating: 4.5,
    loc: "Australia",
    cost: "₹ 20.00",
    distance: 0.2,
    img: venue,
    sport: ["Football", "BasketBall", "Circket"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "Lorem is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    multiImg: [footballground1, venue, footballground2],
  },
  {
    id: 2,
    venueName: "cde Venue",
    rating: 4.5,
    loc: "Delhi",
    cost: "₹ 20.00",
    distance: 3,
    img: venue,
    sport: ["Football", "BasketBall", "Circket"],
    date: "2025-04-19",
    timeSlot: "Evening: 12PM - 6PM",
    desc: "Lorem is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    multiImg: [footballground1, venue, footballground2],
  },
  {
    id: 3,
    venueName: "fgh Venue",
    rating: 4.5,
    loc: "Banglore",
    cost: "₹ 20.00",
    distance: 3,
    img: venue,
    sport: ["Football", "BasketBall", "Circket"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "Lorem is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    multiImg: [footballground1, venue, footballground2],
  },
  {
    id: 4,
    venueName: "ijk Venue",
    rating: 4.5,
    loc: "America",
    cost: "₹ 20.00",
    distance: 3,
    img: venue,
    sport: ["Football", "BasketBall", "Circket"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "Lorem is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    multiImg: [footballground1, venue, footballground2],
  },
  {
    id: 5,
    venueName: "lmn Venue",
    rating: 4.5,
    loc: "Mount Larcom QLD 4695, Australia",
    cost: "₹ 20.00",
    distance: 3,
    img: venue,
    sport: ["Football", "BasketBall", "Circket"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "Lorem is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    multiImg: [footballground1, venue, footballground2],
  },
  {
    id: 6,
    venueName: "opq Venue",
    rating: 4.5,
    loc: "Mount Larcom QLD 4695, Australia",
    cost: "₹ 20.00",
    distance: 3,
    img: venue,
    sport: ["Football", "BasketBall", "Circket"],
    date: "2025-04-11",
    timeSlot: "Morning: 6AM - 12PM",
    desc: "Lorem is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    multiImg: [footballground1, venue, footballground2],
  },
];
